### ISSUE TITLE
v_slam: some animations need to be rerigged

### ISSUE THREAD

**Issue by LychyLychy** [epicplayer40/ManwichsOdysseyAssets#1]
@epicplayer40 
These animation SMDs need to be rigged for the HL2DM V_slam_reference skeleton as they still use the beta skeleton.

- Detonator_stickwall_draw.smd
- stickwall_attach_ND1.smd
- stickwall_attach_ND2.smd
- stickwall_detonate.smd
- stickwall_detonator_holster.smd
- stickwall_draw.smd
- stickwall_draw_ND.smd
- stickwall_to_tripmine.smd
- throw_detonator_holster.smd
- throw_throw_ND1.smd
- throw_throw_ND2.smd
- throw_to_tripmine.smd

Once that is done they need to be uncommented from the qc file then recompiled.
These animations are needed for some activities used by weapon_slam

**Comment by epicplayer40** [comment]
Fixed.
